version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres